using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace R10.Core.DTOs
{
    [Keyless]
    public class DocsOutDTO
    {
        public int DocLogId { get; set; }
        public string? DocumentCode { get; set; }

        [Display(Name ="Document Type")]
        public string? DocumentType { get; set; }

        [Display(Name = "Document")]
        public string? Document { get; set; }

        [Display(Name = "Generated On")]
        public DateTime GeneratedOn { get; set; }

        [Display(Name = "Generated By")]
        public string? GeneratedBy { get; set; }

        public string? SystemType { get; set; }
        public string? ScreenCode { get; set; }
        public int RecKey { get; set; }
        public string? ItemId { get; set; }
        public string? LogFile { get; set; }
        public bool  ForSignature { get; set; }

        [Display(Name = "Sent for eSignature?")]
        public bool  SentToDocuSign { get; set; }
        public int? SignatureQESetupId { get; set; }
        public string? EnvelopeId { get; set; }
        public bool SignatureCompleted { get; set; }
        public string? SignerName { get; set; }
        public string? SignerEmail { get; set; }
        public string? SignerAnchorCode { get; set; }
        public bool SignatureReviewed { get; set; }
    }
}