//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPiEARSCommunication
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", ConfigurationName="CPiEARSCommunication.cpiEARSCommunicationSoap")]
    public interface cpiEARSCommunicationSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication/GetEncryptionK" +
            "ey", ReplyAction="*")]
        System.Threading.Tasks.Task<CPiEARSCommunication.GetEncryptionKeyResponse> GetEncryptionKeyAsync(CPiEARSCommunication.GetEncryptionKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication/ValidateAccoun" +
            "t", ReplyAction="*")]
        System.Threading.Tasks.Task<CPiEARSCommunication.ValidateAccountResponse> ValidateAccountAsync(CPiEARSCommunication.ValidateAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication/GetUserClientC" +
            "odes", ReplyAction="*")]
        System.Threading.Tasks.Task<CPiEARSCommunication.GetUserClientCodesResponse> GetUserClientCodesAsync(CPiEARSCommunication.GetUserClientCodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication/ValidateAccoun" +
            "tAMS", ReplyAction="*")]
        System.Threading.Tasks.Task<CPiEARSCommunication.ValidateAccountAMSResponse> ValidateAccountAMSAsync(CPiEARSCommunication.ValidateAccountAMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication/GetEARSData", ReplyAction="*")]
        System.Threading.Tasks.Task<CPiEARSCommunication.GetEARSDataResponse> GetEARSDataAsync(CPiEARSCommunication.GetEARSDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication/WriteDownloadA" +
            "ctivity", ReplyAction="*")]
        System.Threading.Tasks.Task<CPiEARSCommunication.WriteDownloadActivityResponse> WriteDownloadActivityAsync(CPiEARSCommunication.WriteDownloadActivityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication/EARSUploadInst" +
            "ruction", ReplyAction="*")]
        System.Threading.Tasks.Task<CPiEARSCommunication.EARSUploadInstructionResponse> EARSUploadInstructionAsync(CPiEARSCommunication.EARSUploadInstructionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication/AMSUploadInstr" +
            "uction", ReplyAction="*")]
        System.Threading.Tasks.Task<CPiEARSCommunication.AMSUploadInstructionResponse> AMSUploadInstructionAsync(CPiEARSCommunication.AMSUploadInstructionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication/WriteSession", ReplyAction="*")]
        System.Threading.Tasks.Task<CPiEARSCommunication.WriteSessionResponse> WriteSessionAsync(CPiEARSCommunication.WriteSessionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEncryptionKeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEncryptionKey", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.GetEncryptionKeyRequestBody Body;
        
        public GetEncryptionKeyRequest()
        {
        }
        
        public GetEncryptionKeyRequest(CPiEARSCommunication.GetEncryptionKeyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class GetEncryptionKeyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int intTimeOutInSeconds;
        
        public GetEncryptionKeyRequestBody()
        {
        }
        
        public GetEncryptionKeyRequestBody(int intTimeOutInSeconds)
        {
            this.intTimeOutInSeconds = intTimeOutInSeconds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEncryptionKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEncryptionKeyResponse", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.GetEncryptionKeyResponseBody Body;
        
        public GetEncryptionKeyResponse()
        {
        }
        
        public GetEncryptionKeyResponse(CPiEARSCommunication.GetEncryptionKeyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class GetEncryptionKeyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEncryptionKeyResult;
        
        public GetEncryptionKeyResponseBody()
        {
        }
        
        public GetEncryptionKeyResponseBody(string GetEncryptionKeyResult)
        {
            this.GetEncryptionKeyResult = GetEncryptionKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateAccount", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.ValidateAccountRequestBody Body;
        
        public ValidateAccountRequest()
        {
        }
        
        public ValidateAccountRequest(CPiEARSCommunication.ValidateAccountRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class ValidateAccountRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strEncryptedUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strEncryptedPassword;
        
        public ValidateAccountRequestBody()
        {
        }
        
        public ValidateAccountRequestBody(string strEncryptedUserName, string strEncryptedPassword)
        {
            this.strEncryptedUserName = strEncryptedUserName;
            this.strEncryptedPassword = strEncryptedPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateAccountResponse", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.ValidateAccountResponseBody Body;
        
        public ValidateAccountResponse()
        {
        }
        
        public ValidateAccountResponse(CPiEARSCommunication.ValidateAccountResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class ValidateAccountResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidateAccountResult;
        
        public ValidateAccountResponseBody()
        {
        }
        
        public ValidateAccountResponseBody(string ValidateAccountResult)
        {
            this.ValidateAccountResult = ValidateAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserClientCodesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserClientCodes", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.GetUserClientCodesRequestBody Body;
        
        public GetUserClientCodesRequest()
        {
        }
        
        public GetUserClientCodesRequest(CPiEARSCommunication.GetUserClientCodesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class GetUserClientCodesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strEncryptedEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strEncryptedClientCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strHostAddress;
        
        public GetUserClientCodesRequestBody()
        {
        }
        
        public GetUserClientCodesRequestBody(string strEncryptedEmail, string strEncryptedClientCode, string strHostAddress)
        {
            this.strEncryptedEmail = strEncryptedEmail;
            this.strEncryptedClientCode = strEncryptedClientCode;
            this.strHostAddress = strHostAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserClientCodesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserClientCodesResponse", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.GetUserClientCodesResponseBody Body;
        
        public GetUserClientCodesResponse()
        {
        }
        
        public GetUserClientCodesResponse(CPiEARSCommunication.GetUserClientCodesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class GetUserClientCodesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserClientCodesResult;
        
        public GetUserClientCodesResponseBody()
        {
        }
        
        public GetUserClientCodesResponseBody(string GetUserClientCodesResult)
        {
            this.GetUserClientCodesResult = GetUserClientCodesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateAccountAMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateAccountAMS", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.ValidateAccountAMSRequestBody Body;
        
        public ValidateAccountAMSRequest()
        {
        }
        
        public ValidateAccountAMSRequest(CPiEARSCommunication.ValidateAccountAMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class ValidateAccountAMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strEncryptedEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strEncryptedClientCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool IsModify;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool IsMultiClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strHostAddress;
        
        public ValidateAccountAMSRequestBody()
        {
        }
        
        public ValidateAccountAMSRequestBody(string strEncryptedEmail, string strEncryptedClientCode, bool IsModify, bool IsMultiClient, string strHostAddress)
        {
            this.strEncryptedEmail = strEncryptedEmail;
            this.strEncryptedClientCode = strEncryptedClientCode;
            this.IsModify = IsModify;
            this.IsMultiClient = IsMultiClient;
            this.strHostAddress = strHostAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateAccountAMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateAccountAMSResponse", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.ValidateAccountAMSResponseBody Body;
        
        public ValidateAccountAMSResponse()
        {
        }
        
        public ValidateAccountAMSResponse(CPiEARSCommunication.ValidateAccountAMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class ValidateAccountAMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateAccountAMSResult;
        
        public ValidateAccountAMSResponseBody()
        {
        }
        
        public ValidateAccountAMSResponseBody(bool ValidateAccountAMSResult)
        {
            this.ValidateAccountAMSResult = ValidateAccountAMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEARSDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEARSData", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.GetEARSDataRequestBody Body;
        
        public GetEARSDataRequest()
        {
        }
        
        public GetEARSDataRequest(CPiEARSCommunication.GetEARSDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class GetEARSDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strEARSVersion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strEncryptedClientList;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool blnIncludeParentTables;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dteStartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dteEndDate;
        
        public GetEARSDataRequestBody()
        {
        }
        
        public GetEARSDataRequestBody(string strEARSVersion, string strEncryptedClientList, bool blnIncludeParentTables, System.DateTime dteStartDate, System.DateTime dteEndDate)
        {
            this.strEARSVersion = strEARSVersion;
            this.strEncryptedClientList = strEncryptedClientList;
            this.blnIncludeParentTables = blnIncludeParentTables;
            this.dteStartDate = dteStartDate;
            this.dteEndDate = dteEndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEARSDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEARSDataResponse", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.GetEARSDataResponseBody Body;
        
        public GetEARSDataResponse()
        {
        }
        
        public GetEARSDataResponse(CPiEARSCommunication.GetEARSDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class GetEARSDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetEARSDataResult;
        
        public GetEARSDataResponseBody()
        {
        }
        
        public GetEARSDataResponseBody(byte[] GetEARSDataResult)
        {
            this.GetEARSDataResult = GetEARSDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteDownloadActivityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteDownloadActivity", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.WriteDownloadActivityRequestBody Body;
        
        public WriteDownloadActivityRequest()
        {
        }
        
        public WriteDownloadActivityRequest(CPiEARSCommunication.WriteDownloadActivityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class WriteDownloadActivityRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strEncryptedUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strEncryptedClientList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strCurrentUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] aPostedInfo;
        
        public WriteDownloadActivityRequestBody()
        {
        }
        
        public WriteDownloadActivityRequestBody(string strEncryptedUserName, string strEncryptedClientList, string strCurrentUser, byte[] aPostedInfo)
        {
            this.strEncryptedUserName = strEncryptedUserName;
            this.strEncryptedClientList = strEncryptedClientList;
            this.strCurrentUser = strCurrentUser;
            this.aPostedInfo = aPostedInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteDownloadActivityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteDownloadActivityResponse", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.WriteDownloadActivityResponseBody Body;
        
        public WriteDownloadActivityResponse()
        {
        }
        
        public WriteDownloadActivityResponse(CPiEARSCommunication.WriteDownloadActivityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class WriteDownloadActivityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool WriteDownloadActivityResult;
        
        public WriteDownloadActivityResponseBody()
        {
        }
        
        public WriteDownloadActivityResponseBody(bool WriteDownloadActivityResult)
        {
            this.WriteDownloadActivityResult = WriteDownloadActivityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EARSUploadInstructionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EARSUploadInstruction", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.EARSUploadInstructionRequestBody Body;
        
        public EARSUploadInstructionRequest()
        {
        }
        
        public EARSUploadInstructionRequest(CPiEARSCommunication.EARSUploadInstructionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class EARSUploadInstructionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strEncryptedUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strEncryptedPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int intInstructionCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] aInstructions;
        
        public EARSUploadInstructionRequestBody()
        {
        }
        
        public EARSUploadInstructionRequestBody(string strEncryptedUserName, string strEncryptedPassword, int intInstructionCount, byte[] aInstructions)
        {
            this.strEncryptedUserName = strEncryptedUserName;
            this.strEncryptedPassword = strEncryptedPassword;
            this.intInstructionCount = intInstructionCount;
            this.aInstructions = aInstructions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EARSUploadInstructionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EARSUploadInstructionResponse", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.EARSUploadInstructionResponseBody Body;
        
        public EARSUploadInstructionResponse()
        {
        }
        
        public EARSUploadInstructionResponse(CPiEARSCommunication.EARSUploadInstructionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class EARSUploadInstructionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime EARSUploadInstructionResult;
        
        public EARSUploadInstructionResponseBody()
        {
        }
        
        public EARSUploadInstructionResponseBody(System.DateTime EARSUploadInstructionResult)
        {
            this.EARSUploadInstructionResult = EARSUploadInstructionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AMSUploadInstructionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AMSUploadInstruction", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.AMSUploadInstructionRequestBody Body;
        
        public AMSUploadInstructionRequest()
        {
        }
        
        public AMSUploadInstructionRequest(CPiEARSCommunication.AMSUploadInstructionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class AMSUploadInstructionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strEncryptedUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strEncryptedClientCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int intInstructionCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] aInstructions;
        
        public AMSUploadInstructionRequestBody()
        {
        }
        
        public AMSUploadInstructionRequestBody(string strEncryptedUserName, string strEncryptedClientCode, int intInstructionCount, byte[] aInstructions)
        {
            this.strEncryptedUserName = strEncryptedUserName;
            this.strEncryptedClientCode = strEncryptedClientCode;
            this.intInstructionCount = intInstructionCount;
            this.aInstructions = aInstructions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AMSUploadInstructionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AMSUploadInstructionResponse", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.AMSUploadInstructionResponseBody Body;
        
        public AMSUploadInstructionResponse()
        {
        }
        
        public AMSUploadInstructionResponse(CPiEARSCommunication.AMSUploadInstructionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class AMSUploadInstructionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime AMSUploadInstructionResult;
        
        public AMSUploadInstructionResponseBody()
        {
        }
        
        public AMSUploadInstructionResponseBody(System.DateTime AMSUploadInstructionResult)
        {
            this.AMSUploadInstructionResult = AMSUploadInstructionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteSessionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteSession", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.WriteSessionRequestBody Body;
        
        public WriteSessionRequest()
        {
        }
        
        public WriteSessionRequest(CPiEARSCommunication.WriteSessionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class WriteSessionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strUserName;
        
        public WriteSessionRequestBody()
        {
        }
        
        public WriteSessionRequestBody(string strClient, string strUserName)
        {
            this.strClient = strClient;
            this.strUserName = strUserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteSessionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteSessionResponse", Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication", Order=0)]
        public CPiEARSCommunication.WriteSessionResponseBody Body;
        
        public WriteSessionResponse()
        {
        }
        
        public WriteSessionResponse(CPiEARSCommunication.WriteSessionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ComputerPackages.com/cpiWebService/cpiEARSCommunication")]
    public partial class WriteSessionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int WriteSessionResult;
        
        public WriteSessionResponseBody()
        {
        }
        
        public WriteSessionResponseBody(int WriteSessionResult)
        {
            this.WriteSessionResult = WriteSessionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface cpiEARSCommunicationSoapChannel : CPiEARSCommunication.cpiEARSCommunicationSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class cpiEARSCommunicationSoapClient : System.ServiceModel.ClientBase<CPiEARSCommunication.cpiEARSCommunicationSoap>, CPiEARSCommunication.cpiEARSCommunicationSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public cpiEARSCommunicationSoapClient() : 
                base(cpiEARSCommunicationSoapClient.GetDefaultBinding(), cpiEARSCommunicationSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.cpiEARSCommunicationSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public cpiEARSCommunicationSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(cpiEARSCommunicationSoapClient.GetBindingForEndpoint(endpointConfiguration), cpiEARSCommunicationSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public cpiEARSCommunicationSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(cpiEARSCommunicationSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public cpiEARSCommunicationSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(cpiEARSCommunicationSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public cpiEARSCommunicationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPiEARSCommunication.GetEncryptionKeyResponse> CPiEARSCommunication.cpiEARSCommunicationSoap.GetEncryptionKeyAsync(CPiEARSCommunication.GetEncryptionKeyRequest request)
        {
            return base.Channel.GetEncryptionKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPiEARSCommunication.GetEncryptionKeyResponse> GetEncryptionKeyAsync(int intTimeOutInSeconds)
        {
            CPiEARSCommunication.GetEncryptionKeyRequest inValue = new CPiEARSCommunication.GetEncryptionKeyRequest();
            inValue.Body = new CPiEARSCommunication.GetEncryptionKeyRequestBody();
            inValue.Body.intTimeOutInSeconds = intTimeOutInSeconds;
            return ((CPiEARSCommunication.cpiEARSCommunicationSoap)(this)).GetEncryptionKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPiEARSCommunication.ValidateAccountResponse> CPiEARSCommunication.cpiEARSCommunicationSoap.ValidateAccountAsync(CPiEARSCommunication.ValidateAccountRequest request)
        {
            return base.Channel.ValidateAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPiEARSCommunication.ValidateAccountResponse> ValidateAccountAsync(string strEncryptedUserName, string strEncryptedPassword)
        {
            CPiEARSCommunication.ValidateAccountRequest inValue = new CPiEARSCommunication.ValidateAccountRequest();
            inValue.Body = new CPiEARSCommunication.ValidateAccountRequestBody();
            inValue.Body.strEncryptedUserName = strEncryptedUserName;
            inValue.Body.strEncryptedPassword = strEncryptedPassword;
            return ((CPiEARSCommunication.cpiEARSCommunicationSoap)(this)).ValidateAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPiEARSCommunication.GetUserClientCodesResponse> CPiEARSCommunication.cpiEARSCommunicationSoap.GetUserClientCodesAsync(CPiEARSCommunication.GetUserClientCodesRequest request)
        {
            return base.Channel.GetUserClientCodesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPiEARSCommunication.GetUserClientCodesResponse> GetUserClientCodesAsync(string strEncryptedEmail, string strEncryptedClientCode, string strHostAddress)
        {
            CPiEARSCommunication.GetUserClientCodesRequest inValue = new CPiEARSCommunication.GetUserClientCodesRequest();
            inValue.Body = new CPiEARSCommunication.GetUserClientCodesRequestBody();
            inValue.Body.strEncryptedEmail = strEncryptedEmail;
            inValue.Body.strEncryptedClientCode = strEncryptedClientCode;
            inValue.Body.strHostAddress = strHostAddress;
            return ((CPiEARSCommunication.cpiEARSCommunicationSoap)(this)).GetUserClientCodesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPiEARSCommunication.ValidateAccountAMSResponse> CPiEARSCommunication.cpiEARSCommunicationSoap.ValidateAccountAMSAsync(CPiEARSCommunication.ValidateAccountAMSRequest request)
        {
            return base.Channel.ValidateAccountAMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPiEARSCommunication.ValidateAccountAMSResponse> ValidateAccountAMSAsync(string strEncryptedEmail, string strEncryptedClientCode, bool IsModify, bool IsMultiClient, string strHostAddress)
        {
            CPiEARSCommunication.ValidateAccountAMSRequest inValue = new CPiEARSCommunication.ValidateAccountAMSRequest();
            inValue.Body = new CPiEARSCommunication.ValidateAccountAMSRequestBody();
            inValue.Body.strEncryptedEmail = strEncryptedEmail;
            inValue.Body.strEncryptedClientCode = strEncryptedClientCode;
            inValue.Body.IsModify = IsModify;
            inValue.Body.IsMultiClient = IsMultiClient;
            inValue.Body.strHostAddress = strHostAddress;
            return ((CPiEARSCommunication.cpiEARSCommunicationSoap)(this)).ValidateAccountAMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPiEARSCommunication.GetEARSDataResponse> CPiEARSCommunication.cpiEARSCommunicationSoap.GetEARSDataAsync(CPiEARSCommunication.GetEARSDataRequest request)
        {
            return base.Channel.GetEARSDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPiEARSCommunication.GetEARSDataResponse> GetEARSDataAsync(string strEARSVersion, string strEncryptedClientList, bool blnIncludeParentTables, System.DateTime dteStartDate, System.DateTime dteEndDate)
        {
            CPiEARSCommunication.GetEARSDataRequest inValue = new CPiEARSCommunication.GetEARSDataRequest();
            inValue.Body = new CPiEARSCommunication.GetEARSDataRequestBody();
            inValue.Body.strEARSVersion = strEARSVersion;
            inValue.Body.strEncryptedClientList = strEncryptedClientList;
            inValue.Body.blnIncludeParentTables = blnIncludeParentTables;
            inValue.Body.dteStartDate = dteStartDate;
            inValue.Body.dteEndDate = dteEndDate;
            return ((CPiEARSCommunication.cpiEARSCommunicationSoap)(this)).GetEARSDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPiEARSCommunication.WriteDownloadActivityResponse> CPiEARSCommunication.cpiEARSCommunicationSoap.WriteDownloadActivityAsync(CPiEARSCommunication.WriteDownloadActivityRequest request)
        {
            return base.Channel.WriteDownloadActivityAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPiEARSCommunication.WriteDownloadActivityResponse> WriteDownloadActivityAsync(string strEncryptedUserName, string strEncryptedClientList, string strCurrentUser, byte[] aPostedInfo)
        {
            CPiEARSCommunication.WriteDownloadActivityRequest inValue = new CPiEARSCommunication.WriteDownloadActivityRequest();
            inValue.Body = new CPiEARSCommunication.WriteDownloadActivityRequestBody();
            inValue.Body.strEncryptedUserName = strEncryptedUserName;
            inValue.Body.strEncryptedClientList = strEncryptedClientList;
            inValue.Body.strCurrentUser = strCurrentUser;
            inValue.Body.aPostedInfo = aPostedInfo;
            return ((CPiEARSCommunication.cpiEARSCommunicationSoap)(this)).WriteDownloadActivityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPiEARSCommunication.EARSUploadInstructionResponse> CPiEARSCommunication.cpiEARSCommunicationSoap.EARSUploadInstructionAsync(CPiEARSCommunication.EARSUploadInstructionRequest request)
        {
            return base.Channel.EARSUploadInstructionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPiEARSCommunication.EARSUploadInstructionResponse> EARSUploadInstructionAsync(string strEncryptedUserName, string strEncryptedPassword, int intInstructionCount, byte[] aInstructions)
        {
            CPiEARSCommunication.EARSUploadInstructionRequest inValue = new CPiEARSCommunication.EARSUploadInstructionRequest();
            inValue.Body = new CPiEARSCommunication.EARSUploadInstructionRequestBody();
            inValue.Body.strEncryptedUserName = strEncryptedUserName;
            inValue.Body.strEncryptedPassword = strEncryptedPassword;
            inValue.Body.intInstructionCount = intInstructionCount;
            inValue.Body.aInstructions = aInstructions;
            return ((CPiEARSCommunication.cpiEARSCommunicationSoap)(this)).EARSUploadInstructionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPiEARSCommunication.AMSUploadInstructionResponse> CPiEARSCommunication.cpiEARSCommunicationSoap.AMSUploadInstructionAsync(CPiEARSCommunication.AMSUploadInstructionRequest request)
        {
            return base.Channel.AMSUploadInstructionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPiEARSCommunication.AMSUploadInstructionResponse> AMSUploadInstructionAsync(string strEncryptedUserName, string strEncryptedClientCode, int intInstructionCount, byte[] aInstructions)
        {
            CPiEARSCommunication.AMSUploadInstructionRequest inValue = new CPiEARSCommunication.AMSUploadInstructionRequest();
            inValue.Body = new CPiEARSCommunication.AMSUploadInstructionRequestBody();
            inValue.Body.strEncryptedUserName = strEncryptedUserName;
            inValue.Body.strEncryptedClientCode = strEncryptedClientCode;
            inValue.Body.intInstructionCount = intInstructionCount;
            inValue.Body.aInstructions = aInstructions;
            return ((CPiEARSCommunication.cpiEARSCommunicationSoap)(this)).AMSUploadInstructionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPiEARSCommunication.WriteSessionResponse> CPiEARSCommunication.cpiEARSCommunicationSoap.WriteSessionAsync(CPiEARSCommunication.WriteSessionRequest request)
        {
            return base.Channel.WriteSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPiEARSCommunication.WriteSessionResponse> WriteSessionAsync(string strClient, string strUserName)
        {
            CPiEARSCommunication.WriteSessionRequest inValue = new CPiEARSCommunication.WriteSessionRequest();
            inValue.Body = new CPiEARSCommunication.WriteSessionRequestBody();
            inValue.Body.strClient = strClient;
            inValue.Body.strUserName = strUserName;
            return ((CPiEARSCommunication.cpiEARSCommunicationSoap)(this)).WriteSessionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.cpiEARSCommunicationSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.cpiEARSCommunicationSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://utility.computerpackages.com/cpiWebServices/cpiEARSCommunication.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return cpiEARSCommunicationSoapClient.GetBindingForEndpoint(EndpointConfiguration.cpiEARSCommunicationSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return cpiEARSCommunicationSoapClient.GetEndpointAddress(EndpointConfiguration.cpiEARSCommunicationSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            cpiEARSCommunicationSoap,
        }
    }
}
