using R10.Web.Helpers;
using System.ComponentModel.DataAnnotations;
using static R10.Web.Helpers.ImageHelper;

namespace R10.Web.Areas.Shared.ViewModels
{
    public class DocVerificationCommDocZoomViewModel
    {
        public int DocId { get; set; }
        public int ParentId { get; set; }
        public int InvId { get; set; }

        [Display(Name = "Case Number")]
        public string? CaseNumber { get; set; }
        public string? Country { get; set; }
        [Display(Name = "Sub Case")]
        public string? SubCase { get; set; }
        public string? Title { get; set; }

        public string? DocName { get; set; }
        public string? System { get; set; }
        public string? SystemTypeCode { get; set; }
        public string? ScreenCode { get; set; }
        public string? DocFileName { get; set; }
        public CPiSavedFileType FileType { get; set; }

        public string? jsonQEParam { get; set; }

    }

    public class DocVerificationCommDocQELogViewModel
    {
        public int DocLogId { get; set; }
        public string? DocumentCode { get; set; }

        [Display(Name ="Document Type")]
        public string? DocumentType { get; set; }

        [Display(Name = "Document")]
        public string? Document { get; set; }

        [Display(Name = "Generated On")]
        public DateTime GeneratedOn { get; set; }

        [Display(Name = "Generated By")]
        public string? GeneratedBy { get; set; }

        public string? SystemType { get; set; }
        public string? ScreenCode { get; set; }
        public int RecKey { get; set; }
        public string? ItemId { get; set; }
        public string? LogFile { get; set; }        
        public CPiSavedFileType LogFileType { get; set; }
    }
}