using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace R10.Core.DTOs
{
    [Keyless]
    public class DocEFSLogDetailDTO 
    {
        public int DocId { get; set; }
        
        [Display(Name = "Form Name")]
        public string? FormName { get; set; }

        [Display(Name = "Page No")]
        public Int16 PageNo { get; set; }

        [Display(Name = "Page Count")]
        public Int16 PageCount { get; set; }

        [Display(Name = "Generated On")]
        public DateTime GenDate { get; set; }

        [Display(Name = "Generated By")]
        public string? GenBy { get; set; }

        [Display(Name = "URL/Link")]
        public string? DocUrl { get; set; }
        public string? DocFileName { get; set; }

        [NotMapped]
        public string? DocumentLink { get; set; }
    }
}
