using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace R10.Core.DTOs
{
    [Keyless]
    public class DocLetterLogDetailDTO 
    {
        public int DocId { get; set; }

        [Display(Name = "Letter Name")]
        public string? LetName { get; set; }

        [Display(Name = "Letter Category")]
        public string? LetCatDesc { get; set; }

        [Display(Name = "Generated On")]
        public DateTime GenDate { get; set; }

        [Display(Name = "Generated By")]
        public string? GenBy { get; set; }

        [Display(Name = "Recipients")]
        public string? Recipients { get; set; }
        [Display(Name = "URL/Link")]
        public string? DocUrl { get; set; }
        public string? DocFileName { get; set; }
        
        [NotMapped]
        public string? DocumentLink { get; set; }
    }
}
