using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace R10.Core.DTOs
{
    [Keyless]
    public class DocQELogDetailDTO 
    {
        public int DocId { get; set; }
        
        public string? SystemType { get; set; }
        public string? DataKey { get; set; }
        public int DataKeyValue { get; set; }

        [Display(Name = "Template Name")]
        public string? TemplateName { get; set; }

        [Display(Name = "Subject")]
        public string? Subject { get; set; }
        
        [Display(Name = "From")]
        public string? From { get; set; }
        [Display(Name = "To")]
        public string? To { get; set; }

        [Display(Name = "Reply to")]
        public string? ReplyTo { get; set; }
        [Display(Name = "Copy to")]
        public string? Cc { get; set; }
        [Display(Name = "Blind copy to")]
        public string? Bcc { get; set; }
        
        [Display(Name = "Generated By")]
        public string? GenBy { get; set; }
        [Display(Name = "Generated On")]
        public DateTime GenDate { get; set; }

        [Display(Name = "URL/Link")]
        public string? DocUrl { get; set; }
        public string? DocFileName { get; set; }

        [NotMapped]
        public string? DocumentLink { get; set; }
    }
}
